// ⚠️  GENERATED FILE - DO NOT EDIT
// This file is automatically generated by 'prisma contract emit'.
// To regenerate, run: prisma contract emit
import type { QueryOperationTypes as PgAdapterQueryOps } from '@prisma/orm-postgres/adapter/operation-types';
import type {
  Bit,
  Char,
  CodecTypes as PgTypes,
  Interval,
  JsonValue,
  Numeric,
  Time,
  TimeString,
  Timestamp,
  TimestampString,
  Timestamptz,
  TimestamptzString,
  Timetz,
  VarBit,
  Varchar,
} from '@prisma/orm-postgres/target/codec-types';

import type {
  ContractWithTypeMaps,
  TypeMaps as TypeMapsType,
} from '@prisma/orm-postgres/family-contract/types';
import type {
  Contract as ContractType,
  ExecutionHashBase,
  NamespaceId,
  ProfileHashBase,
  StorageHashBase,
} from '@prisma/orm-postgres/contract/types';

export type StorageHash =
  StorageHashBase<'1ccc0a773b31915bc8d807dafeb65f27ba3329d13141b88c35c05d254b366223'>;
export type ExecutionHash =
  ExecutionHashBase<'6e9cc05f2c9a97430df25ad3dcedddcca99a6fef36d6cef01a9f07027dc5e2e3'>;
export type ProfileHash =
  ProfileHashBase<'3916f444a8a17ad749191acf9e08dad97d1a327b88c2f1d45d12f240296aa8b2'>;

export type CodecTypes = PgTypes;
export type LaneCodecTypes = CodecTypes;
export type QueryOperationTypes = PgAdapterQueryOps<CodecTypes>;
export type AggregateTypes = {
  readonly avg: {
    readonly byCodec: {
      readonly 'pg/float@1': { readonly output: 'pg/float8@1'; readonly nullable: true };
      readonly 'pg/float4@1': { readonly output: 'pg/float8@1'; readonly nullable: true };
      readonly 'pg/float8@1': { readonly output: 'pg/float8@1'; readonly nullable: true };
      readonly 'pg/int@1': { readonly output: 'pg/float8@1'; readonly nullable: true };
      readonly 'pg/int2@1': { readonly output: 'pg/float8@1'; readonly nullable: true };
      readonly 'pg/int4@1': { readonly output: 'pg/float8@1'; readonly nullable: true };
      readonly 'pg/int8@1': { readonly output: 'pg/float8@1'; readonly nullable: true };
      readonly 'pg/int8number@1': { readonly output: 'pg/float8@1'; readonly nullable: true };
      readonly 'pg/interval@1': { readonly output: 'pg/interval@1'; readonly nullable: true };
      readonly 'pg/numeric@1': { readonly output: 'pg/numeric@1'; readonly nullable: true };
      readonly 'pg/time-string@1': { readonly output: 'pg/interval@1'; readonly nullable: true };
      readonly 'pg/time-temporal@1': { readonly output: 'pg/interval@1'; readonly nullable: true };
      readonly 'pg/unboundedint@1': { readonly output: 'pg/float8@1'; readonly nullable: true };
      readonly 'sql/float@1': { readonly output: 'pg/float8@1'; readonly nullable: true };
      readonly 'sql/int@1': { readonly output: 'pg/float8@1'; readonly nullable: true };
    };
  };
  readonly avgDecimal: {
    readonly byCodec: {
      readonly 'pg/int@1': { readonly output: 'pg/numeric@1'; readonly nullable: true };
      readonly 'pg/int2@1': { readonly output: 'pg/numeric@1'; readonly nullable: true };
      readonly 'pg/int4@1': { readonly output: 'pg/numeric@1'; readonly nullable: true };
      readonly 'pg/int8@1': { readonly output: 'pg/numeric@1'; readonly nullable: true };
      readonly 'pg/int8number@1': { readonly output: 'pg/numeric@1'; readonly nullable: true };
      readonly 'pg/numeric@1': { readonly output: 'pg/numeric@1'; readonly nullable: true };
      readonly 'pg/unboundedint@1': { readonly output: 'pg/numeric@1'; readonly nullable: true };
      readonly 'sql/int@1': { readonly output: 'pg/numeric@1'; readonly nullable: true };
    };
  };
  readonly count: {
    readonly byCodec: {};
    readonly withoutInput: { readonly output: 'pg/int8number@1'; readonly nullable: false };
    readonly anyInput: { readonly output: 'pg/int8number@1'; readonly nullable: false };
  };
  readonly countBigInt: {
    readonly byCodec: {};
    readonly withoutInput: { readonly output: 'pg/int8@1'; readonly nullable: false };
    readonly anyInput: { readonly output: 'pg/int8@1'; readonly nullable: false };
  };
  readonly max: {
    readonly byCodec: {
      readonly 'pg/char@1': { readonly output: 'pg/char@1'; readonly nullable: true };
      readonly 'pg/date-string@1': { readonly output: 'pg/date-string@1'; readonly nullable: true };
      readonly 'pg/date-temporal@1': {
        readonly output: 'pg/date-temporal@1';
        readonly nullable: true;
      };
      readonly 'pg/enum@1': { readonly output: 'pg/enum@1'; readonly nullable: true };
      readonly 'pg/float@1': { readonly output: 'pg/float@1'; readonly nullable: true };
      readonly 'pg/float4@1': { readonly output: 'pg/float4@1'; readonly nullable: true };
      readonly 'pg/float8@1': { readonly output: 'pg/float8@1'; readonly nullable: true };
      readonly 'pg/inet@1': { readonly output: 'pg/inet@1'; readonly nullable: true };
      readonly 'pg/int@1': { readonly output: 'pg/int@1'; readonly nullable: true };
      readonly 'pg/int2@1': { readonly output: 'pg/int2@1'; readonly nullable: true };
      readonly 'pg/int4@1': { readonly output: 'pg/int4@1'; readonly nullable: true };
      readonly 'pg/int8@1': { readonly output: 'pg/int8@1'; readonly nullable: true };
      readonly 'pg/int8number@1': { readonly output: 'pg/int8number@1'; readonly nullable: true };
      readonly 'pg/interval@1': { readonly output: 'pg/interval@1'; readonly nullable: true };
      readonly 'pg/numeric@1': { readonly output: 'pg/numeric@1'; readonly nullable: true };
      readonly 'pg/text-array@1': { readonly output: 'pg/text-array@1'; readonly nullable: true };
      readonly 'pg/text@1': { readonly output: 'pg/text@1'; readonly nullable: true };
      readonly 'pg/time-string@1': { readonly output: 'pg/time-string@1'; readonly nullable: true };
      readonly 'pg/time-temporal@1': {
        readonly output: 'pg/time-temporal@1';
        readonly nullable: true;
      };
      readonly 'pg/timestamp-string@1': {
        readonly output: 'pg/timestamp-string@1';
        readonly nullable: true;
      };
      readonly 'pg/timestamp-temporal@1': {
        readonly output: 'pg/timestamp-temporal@1';
        readonly nullable: true;
      };
      readonly 'pg/timestamptz-string@1': {
        readonly output: 'pg/timestamptz-string@1';
        readonly nullable: true;
      };
      readonly 'pg/timestamptz-temporal@1': {
        readonly output: 'pg/timestamptz-temporal@1';
        readonly nullable: true;
      };
      readonly 'pg/timetz@1': { readonly output: 'pg/timetz@1'; readonly nullable: true };
      readonly 'pg/unboundedint@1': {
        readonly output: 'pg/unboundedint@1';
        readonly nullable: true;
      };
      readonly 'pg/varchar@1': { readonly output: 'pg/text@1'; readonly nullable: true };
      readonly 'sql/char@1': { readonly output: 'sql/char@1'; readonly nullable: true };
      readonly 'sql/float@1': { readonly output: 'sql/float@1'; readonly nullable: true };
      readonly 'sql/int@1': { readonly output: 'sql/int@1'; readonly nullable: true };
      readonly 'sql/text@1': { readonly output: 'sql/text@1'; readonly nullable: true };
      readonly 'sql/varchar@1': { readonly output: 'pg/text@1'; readonly nullable: true };
    };
  };
  readonly min: {
    readonly byCodec: {
      readonly 'pg/char@1': { readonly output: 'pg/char@1'; readonly nullable: true };
      readonly 'pg/date-string@1': { readonly output: 'pg/date-string@1'; readonly nullable: true };
      readonly 'pg/date-temporal@1': {
        readonly output: 'pg/date-temporal@1';
        readonly nullable: true;
      };
      readonly 'pg/enum@1': { readonly output: 'pg/enum@1'; readonly nullable: true };
      readonly 'pg/float@1': { readonly output: 'pg/float@1'; readonly nullable: true };
      readonly 'pg/float4@1': { readonly output: 'pg/float4@1'; readonly nullable: true };
      readonly 'pg/float8@1': { readonly output: 'pg/float8@1'; readonly nullable: true };
      readonly 'pg/inet@1': { readonly output: 'pg/inet@1'; readonly nullable: true };
      readonly 'pg/int@1': { readonly output: 'pg/int@1'; readonly nullable: true };
      readonly 'pg/int2@1': { readonly output: 'pg/int2@1'; readonly nullable: true };
      readonly 'pg/int4@1': { readonly output: 'pg/int4@1'; readonly nullable: true };
      readonly 'pg/int8@1': { readonly output: 'pg/int8@1'; readonly nullable: true };
      readonly 'pg/int8number@1': { readonly output: 'pg/int8number@1'; readonly nullable: true };
      readonly 'pg/interval@1': { readonly output: 'pg/interval@1'; readonly nullable: true };
      readonly 'pg/numeric@1': { readonly output: 'pg/numeric@1'; readonly nullable: true };
      readonly 'pg/text-array@1': { readonly output: 'pg/text-array@1'; readonly nullable: true };
      readonly 'pg/text@1': { readonly output: 'pg/text@1'; readonly nullable: true };
      readonly 'pg/time-string@1': { readonly output: 'pg/time-string@1'; readonly nullable: true };
      readonly 'pg/time-temporal@1': {
        readonly output: 'pg/time-temporal@1';
        readonly nullable: true;
      };
      readonly 'pg/timestamp-string@1': {
        readonly output: 'pg/timestamp-string@1';
        readonly nullable: true;
      };
      readonly 'pg/timestamp-temporal@1': {
        readonly output: 'pg/timestamp-temporal@1';
        readonly nullable: true;
      };
      readonly 'pg/timestamptz-string@1': {
        readonly output: 'pg/timestamptz-string@1';
        readonly nullable: true;
      };
      readonly 'pg/timestamptz-temporal@1': {
        readonly output: 'pg/timestamptz-temporal@1';
        readonly nullable: true;
      };
      readonly 'pg/timetz@1': { readonly output: 'pg/timetz@1'; readonly nullable: true };
      readonly 'pg/unboundedint@1': {
        readonly output: 'pg/unboundedint@1';
        readonly nullable: true;
      };
      readonly 'pg/varchar@1': { readonly output: 'pg/text@1'; readonly nullable: true };
      readonly 'sql/char@1': { readonly output: 'sql/char@1'; readonly nullable: true };
      readonly 'sql/float@1': { readonly output: 'sql/float@1'; readonly nullable: true };
      readonly 'sql/int@1': { readonly output: 'sql/int@1'; readonly nullable: true };
      readonly 'sql/text@1': { readonly output: 'sql/text@1'; readonly nullable: true };
      readonly 'sql/varchar@1': { readonly output: 'pg/text@1'; readonly nullable: true };
    };
  };
  readonly sum: {
    readonly byCodec: {
      readonly 'pg/float@1': { readonly output: 'pg/float8@1'; readonly nullable: true };
      readonly 'pg/float4@1': { readonly output: 'pg/float4@1'; readonly nullable: true };
      readonly 'pg/float8@1': { readonly output: 'pg/float8@1'; readonly nullable: true };
      readonly 'pg/int@1': { readonly output: 'pg/int8number@1'; readonly nullable: true };
      readonly 'pg/int2@1': { readonly output: 'pg/int8number@1'; readonly nullable: true };
      readonly 'pg/int4@1': { readonly output: 'pg/int8number@1'; readonly nullable: true };
      readonly 'pg/int8@1': { readonly output: 'pg/int8number@1'; readonly nullable: true };
      readonly 'pg/int8number@1': { readonly output: 'pg/int8number@1'; readonly nullable: true };
      readonly 'pg/interval@1': { readonly output: 'pg/interval@1'; readonly nullable: true };
      readonly 'pg/numeric@1': { readonly output: 'pg/numeric@1'; readonly nullable: true };
      readonly 'pg/time-string@1': { readonly output: 'pg/interval@1'; readonly nullable: true };
      readonly 'pg/time-temporal@1': { readonly output: 'pg/interval@1'; readonly nullable: true };
      readonly 'pg/unboundedint@1': {
        readonly output: 'pg/unboundedint@1';
        readonly nullable: true;
      };
      readonly 'sql/float@1': { readonly output: 'pg/float8@1'; readonly nullable: true };
      readonly 'sql/int@1': { readonly output: 'pg/int8number@1'; readonly nullable: true };
    };
  };
  readonly sumBigInt: {
    readonly byCodec: {
      readonly 'pg/int@1': { readonly output: 'pg/int8@1'; readonly nullable: true };
      readonly 'pg/int2@1': { readonly output: 'pg/int8@1'; readonly nullable: true };
      readonly 'pg/int4@1': { readonly output: 'pg/int8@1'; readonly nullable: true };
      readonly 'pg/int8@1': { readonly output: 'pg/unboundedint@1'; readonly nullable: true };
      readonly 'pg/int8number@1': { readonly output: 'pg/unboundedint@1'; readonly nullable: true };
      readonly 'pg/unboundedint@1': {
        readonly output: 'pg/unboundedint@1';
        readonly nullable: true;
      };
      readonly 'sql/int@1': { readonly output: 'pg/int8@1'; readonly nullable: true };
    };
  };
};
type DefaultLiteralValue<CodecId extends string, Encoded> = CodecId extends keyof CodecTypes
  ? Encoded extends CodecTypes[CodecId]['json']
    ? Encoded
    : CodecTypes[CodecId]['json']
  : Encoded;

export type FieldOutputTypes = {
  readonly public: {
    readonly Auditoria: {
      readonly id: CodecTypes['pg/text@1']['output'];
      readonly usuarioId: CodecTypes['pg/text@1']['output'];
      readonly accion: CodecTypes['pg/text@1']['output'];
      readonly entidad: CodecTypes['pg/text@1']['output'];
      readonly entidadId: CodecTypes['pg/text@1']['output'];
      readonly detalles: CodecTypes['pg/text@1']['output'];
      readonly ip: CodecTypes['pg/text@1']['output'] | null;
      readonly timestamp: CodecTypes['pg/timestamptz-temporal@1']['output'];
    };
    readonly Dispensado: {
      readonly id: CodecTypes['pg/text@1']['output'];
      readonly ordenId: CodecTypes['pg/text@1']['output'];
      readonly loteId: CodecTypes['pg/text@1']['output'];
      readonly operarioId: CodecTypes['pg/text@1']['output'];
      readonly materialNombre: CodecTypes['pg/text@1']['output'];
      readonly cantidadTarget: CodecTypes['pg/float8@1']['output'];
      readonly cantidadReal: CodecTypes['pg/float8@1']['output'];
      readonly toleranciaOk: CodecTypes['pg/bool@1']['output'];
      readonly paso: CodecTypes['pg/int4@1']['output'];
      readonly firmaElectronica: CodecTypes['pg/text@1']['output'] | null;
      readonly supervisorId: CodecTypes['pg/text@1']['output'] | null;
      readonly timestamp: CodecTypes['pg/timestamptz-temporal@1']['output'];
    };
    readonly Ingrediente: {
      readonly id: CodecTypes['pg/text@1']['output'];
      readonly recetaId: CodecTypes['pg/text@1']['output'];
      readonly materialId: CodecTypes['pg/text@1']['output'];
      readonly orden: CodecTypes['pg/int4@1']['output'];
      readonly cantidadTarget: CodecTypes['pg/float8@1']['output'];
      readonly toleranciaMin: CodecTypes['pg/float8@1']['output'];
      readonly toleranciaMax: CodecTypes['pg/float8@1']['output'];
      readonly instrucciones: CodecTypes['pg/text@1']['output'] | null;
      readonly peligroso: CodecTypes['pg/bool@1']['output'];
    };
    readonly Lote: {
      readonly id: CodecTypes['pg/text@1']['output'];
      readonly numero: CodecTypes['pg/text@1']['output'];
      readonly materialId: CodecTypes['pg/text@1']['output'];
      readonly cantidad: CodecTypes['pg/float8@1']['output'];
      readonly cantidadInicial: CodecTypes['pg/float8@1']['output'];
      readonly fechaRecepcion: CodecTypes['pg/timestamptz-temporal@1']['output'];
      readonly fechaCaducidad: CodecTypes['pg/timestamptz-temporal@1']['output'];
      readonly proveedor: CodecTypes['pg/text@1']['output'];
      readonly estado: CodecTypes['pg/text@1']['output'];
      readonly certificado: CodecTypes['pg/text@1']['output'] | null;
      readonly createdAt: CodecTypes['pg/timestamptz-temporal@1']['output'];
    };
    readonly Material: {
      readonly id: CodecTypes['pg/text@1']['output'];
      readonly codigo: CodecTypes['pg/text@1']['output'];
      readonly nombre: CodecTypes['pg/text@1']['output'];
      readonly descripcion: CodecTypes['pg/text@1']['output'] | null;
      readonly unidad: CodecTypes['pg/text@1']['output'];
      readonly stockMinimo: CodecTypes['pg/float8@1']['output'];
      readonly activo: CodecTypes['pg/bool@1']['output'];
    };
    readonly OrdenProduccion: {
      readonly id: CodecTypes['pg/text@1']['output'];
      readonly numero: CodecTypes['pg/text@1']['output'];
      readonly recetaId: CodecTypes['pg/text@1']['output'];
      readonly loteProducto: CodecTypes['pg/text@1']['output'];
      readonly cantidad: CodecTypes['pg/float8@1']['output'];
      readonly estado: CodecTypes['pg/text@1']['output'];
      readonly prioridad: CodecTypes['pg/int4@1']['output'];
      readonly createdAt: CodecTypes['pg/timestamptz-temporal@1']['output'];
      readonly updatedAt: CodecTypes['pg/timestamptz-temporal@1']['output'];
    };
    readonly Receta: {
      readonly id: CodecTypes['pg/text@1']['output'];
      readonly codigo: CodecTypes['pg/text@1']['output'];
      readonly nombre: CodecTypes['pg/text@1']['output'];
      readonly version: CodecTypes['pg/int4@1']['output'];
      readonly descripcion: CodecTypes['pg/text@1']['output'] | null;
      readonly rendimiento: CodecTypes['pg/float8@1']['output'];
      readonly unidadRendimiento: CodecTypes['pg/text@1']['output'];
      readonly activa: CodecTypes['pg/bool@1']['output'];
      readonly createdAt: CodecTypes['pg/timestamptz-temporal@1']['output'];
      readonly updatedAt: CodecTypes['pg/timestamptz-temporal@1']['output'];
    };
    readonly Usuario: {
      readonly id: CodecTypes['pg/text@1']['output'];
      readonly nombre: CodecTypes['pg/text@1']['output'];
      readonly email: CodecTypes['pg/text@1']['output'];
      readonly password: CodecTypes['pg/text@1']['output'];
      readonly rol: CodecTypes['pg/text@1']['output'];
      readonly badge: CodecTypes['pg/text@1']['output'] | null;
      readonly activo: CodecTypes['pg/bool@1']['output'];
      readonly createdAt: CodecTypes['pg/timestamptz-temporal@1']['output'];
    };
  };
};
export type FieldInputTypes = {
  readonly public: {
    readonly Auditoria: {
      readonly id: CodecTypes['pg/text@1']['input'];
      readonly usuarioId: CodecTypes['pg/text@1']['input'];
      readonly accion: CodecTypes['pg/text@1']['input'];
      readonly entidad: CodecTypes['pg/text@1']['input'];
      readonly entidadId: CodecTypes['pg/text@1']['input'];
      readonly detalles: CodecTypes['pg/text@1']['input'];
      readonly ip: CodecTypes['pg/text@1']['input'] | null;
      readonly timestamp: CodecTypes['pg/timestamptz-temporal@1']['input'];
    };
    readonly Dispensado: {
      readonly id: CodecTypes['pg/text@1']['input'];
      readonly ordenId: CodecTypes['pg/text@1']['input'];
      readonly loteId: CodecTypes['pg/text@1']['input'];
      readonly operarioId: CodecTypes['pg/text@1']['input'];
      readonly materialNombre: CodecTypes['pg/text@1']['input'];
      readonly cantidadTarget: CodecTypes['pg/float8@1']['input'];
      readonly cantidadReal: CodecTypes['pg/float8@1']['input'];
      readonly toleranciaOk: CodecTypes['pg/bool@1']['input'];
      readonly paso: CodecTypes['pg/int4@1']['input'];
      readonly firmaElectronica: CodecTypes['pg/text@1']['input'] | null;
      readonly supervisorId: CodecTypes['pg/text@1']['input'] | null;
      readonly timestamp: CodecTypes['pg/timestamptz-temporal@1']['input'];
    };
    readonly Ingrediente: {
      readonly id: CodecTypes['pg/text@1']['input'];
      readonly recetaId: CodecTypes['pg/text@1']['input'];
      readonly materialId: CodecTypes['pg/text@1']['input'];
      readonly orden: CodecTypes['pg/int4@1']['input'];
      readonly cantidadTarget: CodecTypes['pg/float8@1']['input'];
      readonly toleranciaMin: CodecTypes['pg/float8@1']['input'];
      readonly toleranciaMax: CodecTypes['pg/float8@1']['input'];
      readonly instrucciones: CodecTypes['pg/text@1']['input'] | null;
      readonly peligroso: CodecTypes['pg/bool@1']['input'];
    };
    readonly Lote: {
      readonly id: CodecTypes['pg/text@1']['input'];
      readonly numero: CodecTypes['pg/text@1']['input'];
      readonly materialId: CodecTypes['pg/text@1']['input'];
      readonly cantidad: CodecTypes['pg/float8@1']['input'];
      readonly cantidadInicial: CodecTypes['pg/float8@1']['input'];
      readonly fechaRecepcion: CodecTypes['pg/timestamptz-temporal@1']['input'];
      readonly fechaCaducidad: CodecTypes['pg/timestamptz-temporal@1']['input'];
      readonly proveedor: CodecTypes['pg/text@1']['input'];
      readonly estado: CodecTypes['pg/text@1']['input'];
      readonly certificado: CodecTypes['pg/text@1']['input'] | null;
      readonly createdAt: CodecTypes['pg/timestamptz-temporal@1']['input'];
    };
    readonly Material: {
      readonly id: CodecTypes['pg/text@1']['input'];
      readonly codigo: CodecTypes['pg/text@1']['input'];
      readonly nombre: CodecTypes['pg/text@1']['input'];
      readonly descripcion: CodecTypes['pg/text@1']['input'] | null;
      readonly unidad: CodecTypes['pg/text@1']['input'];
      readonly stockMinimo: CodecTypes['pg/float8@1']['input'];
      readonly activo: CodecTypes['pg/bool@1']['input'];
    };
    readonly OrdenProduccion: {
      readonly id: CodecTypes['pg/text@1']['input'];
      readonly numero: CodecTypes['pg/text@1']['input'];
      readonly recetaId: CodecTypes['pg/text@1']['input'];
      readonly loteProducto: CodecTypes['pg/text@1']['input'];
      readonly cantidad: CodecTypes['pg/float8@1']['input'];
      readonly estado: CodecTypes['pg/text@1']['input'];
      readonly prioridad: CodecTypes['pg/int4@1']['input'];
      readonly createdAt: CodecTypes['pg/timestamptz-temporal@1']['input'];
      readonly updatedAt: CodecTypes['pg/timestamptz-temporal@1']['input'];
    };
    readonly Receta: {
      readonly id: CodecTypes['pg/text@1']['input'];
      readonly codigo: CodecTypes['pg/text@1']['input'];
      readonly nombre: CodecTypes['pg/text@1']['input'];
      readonly version: CodecTypes['pg/int4@1']['input'];
      readonly descripcion: CodecTypes['pg/text@1']['input'] | null;
      readonly rendimiento: CodecTypes['pg/float8@1']['input'];
      readonly unidadRendimiento: CodecTypes['pg/text@1']['input'];
      readonly activa: CodecTypes['pg/bool@1']['input'];
      readonly createdAt: CodecTypes['pg/timestamptz-temporal@1']['input'];
      readonly updatedAt: CodecTypes['pg/timestamptz-temporal@1']['input'];
    };
    readonly Usuario: {
      readonly id: CodecTypes['pg/text@1']['input'];
      readonly nombre: CodecTypes['pg/text@1']['input'];
      readonly email: CodecTypes['pg/text@1']['input'];
      readonly password: CodecTypes['pg/text@1']['input'];
      readonly rol: CodecTypes['pg/text@1']['input'];
      readonly badge: CodecTypes['pg/text@1']['input'] | null;
      readonly activo: CodecTypes['pg/bool@1']['input'];
      readonly createdAt: CodecTypes['pg/timestamptz-temporal@1']['input'];
    };
  };
};
export type StorageColumnTypes = {
  readonly public: {
    readonly auditoria: {
      readonly accion: CodecTypes['pg/text@1']['output'];
      readonly detalles: CodecTypes['pg/text@1']['output'];
      readonly entidad: CodecTypes['pg/text@1']['output'];
      readonly entidadId: CodecTypes['pg/text@1']['output'];
      readonly id: CodecTypes['pg/text@1']['output'];
      readonly ip: CodecTypes['pg/text@1']['output'] | null;
      readonly timestamp: CodecTypes['pg/timestamptz-temporal@1']['output'];
      readonly usuarioId: CodecTypes['pg/text@1']['output'];
    };
    readonly dispensado: {
      readonly cantidadReal: CodecTypes['pg/float8@1']['output'];
      readonly cantidadTarget: CodecTypes['pg/float8@1']['output'];
      readonly firmaElectronica: CodecTypes['pg/text@1']['output'] | null;
      readonly id: CodecTypes['pg/text@1']['output'];
      readonly loteId: CodecTypes['pg/text@1']['output'];
      readonly materialNombre: CodecTypes['pg/text@1']['output'];
      readonly operarioId: CodecTypes['pg/text@1']['output'];
      readonly ordenId: CodecTypes['pg/text@1']['output'];
      readonly paso: CodecTypes['pg/int4@1']['output'];
      readonly supervisorId: CodecTypes['pg/text@1']['output'] | null;
      readonly timestamp: CodecTypes['pg/timestamptz-temporal@1']['output'];
      readonly toleranciaOk: CodecTypes['pg/bool@1']['output'];
    };
    readonly ingrediente: {
      readonly cantidadTarget: CodecTypes['pg/float8@1']['output'];
      readonly id: CodecTypes['pg/text@1']['output'];
      readonly instrucciones: CodecTypes['pg/text@1']['output'] | null;
      readonly materialId: CodecTypes['pg/text@1']['output'];
      readonly orden: CodecTypes['pg/int4@1']['output'];
      readonly peligroso: CodecTypes['pg/bool@1']['output'];
      readonly recetaId: CodecTypes['pg/text@1']['output'];
      readonly toleranciaMax: CodecTypes['pg/float8@1']['output'];
      readonly toleranciaMin: CodecTypes['pg/float8@1']['output'];
    };
    readonly lote: {
      readonly cantidad: CodecTypes['pg/float8@1']['output'];
      readonly cantidadInicial: CodecTypes['pg/float8@1']['output'];
      readonly certificado: CodecTypes['pg/text@1']['output'] | null;
      readonly createdAt: CodecTypes['pg/timestamptz-temporal@1']['output'];
      readonly estado: CodecTypes['pg/text@1']['output'];
      readonly fechaCaducidad: CodecTypes['pg/timestamptz-temporal@1']['output'];
      readonly fechaRecepcion: CodecTypes['pg/timestamptz-temporal@1']['output'];
      readonly id: CodecTypes['pg/text@1']['output'];
      readonly materialId: CodecTypes['pg/text@1']['output'];
      readonly numero: CodecTypes['pg/text@1']['output'];
      readonly proveedor: CodecTypes['pg/text@1']['output'];
    };
    readonly material: {
      readonly activo: CodecTypes['pg/bool@1']['output'];
      readonly codigo: CodecTypes['pg/text@1']['output'];
      readonly descripcion: CodecTypes['pg/text@1']['output'] | null;
      readonly id: CodecTypes['pg/text@1']['output'];
      readonly nombre: CodecTypes['pg/text@1']['output'];
      readonly stockMinimo: CodecTypes['pg/float8@1']['output'];
      readonly unidad: CodecTypes['pg/text@1']['output'];
    };
    readonly ordenProduccion: {
      readonly cantidad: CodecTypes['pg/float8@1']['output'];
      readonly createdAt: CodecTypes['pg/timestamptz-temporal@1']['output'];
      readonly estado: CodecTypes['pg/text@1']['output'];
      readonly id: CodecTypes['pg/text@1']['output'];
      readonly loteProducto: CodecTypes['pg/text@1']['output'];
      readonly numero: CodecTypes['pg/text@1']['output'];
      readonly prioridad: CodecTypes['pg/int4@1']['output'];
      readonly recetaId: CodecTypes['pg/text@1']['output'];
      readonly updatedAt: CodecTypes['pg/timestamptz-temporal@1']['output'];
    };
    readonly receta: {
      readonly activa: CodecTypes['pg/bool@1']['output'];
      readonly codigo: CodecTypes['pg/text@1']['output'];
      readonly createdAt: CodecTypes['pg/timestamptz-temporal@1']['output'];
      readonly descripcion: CodecTypes['pg/text@1']['output'] | null;
      readonly id: CodecTypes['pg/text@1']['output'];
      readonly nombre: CodecTypes['pg/text@1']['output'];
      readonly rendimiento: CodecTypes['pg/float8@1']['output'];
      readonly unidadRendimiento: CodecTypes['pg/text@1']['output'];
      readonly updatedAt: CodecTypes['pg/timestamptz-temporal@1']['output'];
      readonly version: CodecTypes['pg/int4@1']['output'];
    };
    readonly usuario: {
      readonly activo: CodecTypes['pg/bool@1']['output'];
      readonly badge: CodecTypes['pg/text@1']['output'] | null;
      readonly createdAt: CodecTypes['pg/timestamptz-temporal@1']['output'];
      readonly email: CodecTypes['pg/text@1']['output'];
      readonly id: CodecTypes['pg/text@1']['output'];
      readonly nombre: CodecTypes['pg/text@1']['output'];
      readonly password: CodecTypes['pg/text@1']['output'];
      readonly rol: CodecTypes['pg/text@1']['output'];
    };
  };
};
export type StorageColumnInputTypes = {
  readonly public: {
    readonly auditoria: {
      readonly accion: CodecTypes['pg/text@1']['input'];
      readonly detalles: CodecTypes['pg/text@1']['input'];
      readonly entidad: CodecTypes['pg/text@1']['input'];
      readonly entidadId: CodecTypes['pg/text@1']['input'];
      readonly id: CodecTypes['pg/text@1']['input'];
      readonly ip: CodecTypes['pg/text@1']['input'] | null;
      readonly timestamp: CodecTypes['pg/timestamptz-temporal@1']['input'];
      readonly usuarioId: CodecTypes['pg/text@1']['input'];
    };
    readonly dispensado: {
      readonly cantidadReal: CodecTypes['pg/float8@1']['input'];
      readonly cantidadTarget: CodecTypes['pg/float8@1']['input'];
      readonly firmaElectronica: CodecTypes['pg/text@1']['input'] | null;
      readonly id: CodecTypes['pg/text@1']['input'];
      readonly loteId: CodecTypes['pg/text@1']['input'];
      readonly materialNombre: CodecTypes['pg/text@1']['input'];
      readonly operarioId: CodecTypes['pg/text@1']['input'];
      readonly ordenId: CodecTypes['pg/text@1']['input'];
      readonly paso: CodecTypes['pg/int4@1']['input'];
      readonly supervisorId: CodecTypes['pg/text@1']['input'] | null;
      readonly timestamp: CodecTypes['pg/timestamptz-temporal@1']['input'];
      readonly toleranciaOk: CodecTypes['pg/bool@1']['input'];
    };
    readonly ingrediente: {
      readonly cantidadTarget: CodecTypes['pg/float8@1']['input'];
      readonly id: CodecTypes['pg/text@1']['input'];
      readonly instrucciones: CodecTypes['pg/text@1']['input'] | null;
      readonly materialId: CodecTypes['pg/text@1']['input'];
      readonly orden: CodecTypes['pg/int4@1']['input'];
      readonly peligroso: CodecTypes['pg/bool@1']['input'];
      readonly recetaId: CodecTypes['pg/text@1']['input'];
      readonly toleranciaMax: CodecTypes['pg/float8@1']['input'];
      readonly toleranciaMin: CodecTypes['pg/float8@1']['input'];
    };
    readonly lote: {
      readonly cantidad: CodecTypes['pg/float8@1']['input'];
      readonly cantidadInicial: CodecTypes['pg/float8@1']['input'];
      readonly certificado: CodecTypes['pg/text@1']['input'] | null;
      readonly createdAt: CodecTypes['pg/timestamptz-temporal@1']['input'];
      readonly estado: CodecTypes['pg/text@1']['input'];
      readonly fechaCaducidad: CodecTypes['pg/timestamptz-temporal@1']['input'];
      readonly fechaRecepcion: CodecTypes['pg/timestamptz-temporal@1']['input'];
      readonly id: CodecTypes['pg/text@1']['input'];
      readonly materialId: CodecTypes['pg/text@1']['input'];
      readonly numero: CodecTypes['pg/text@1']['input'];
      readonly proveedor: CodecTypes['pg/text@1']['input'];
    };
    readonly material: {
      readonly activo: CodecTypes['pg/bool@1']['input'];
      readonly codigo: CodecTypes['pg/text@1']['input'];
      readonly descripcion: CodecTypes['pg/text@1']['input'] | null;
      readonly id: CodecTypes['pg/text@1']['input'];
      readonly nombre: CodecTypes['pg/text@1']['input'];
      readonly stockMinimo: CodecTypes['pg/float8@1']['input'];
      readonly unidad: CodecTypes['pg/text@1']['input'];
    };
    readonly ordenProduccion: {
      readonly cantidad: CodecTypes['pg/float8@1']['input'];
      readonly createdAt: CodecTypes['pg/timestamptz-temporal@1']['input'];
      readonly estado: CodecTypes['pg/text@1']['input'];
      readonly id: CodecTypes['pg/text@1']['input'];
      readonly loteProducto: CodecTypes['pg/text@1']['input'];
      readonly numero: CodecTypes['pg/text@1']['input'];
      readonly prioridad: CodecTypes['pg/int4@1']['input'];
      readonly recetaId: CodecTypes['pg/text@1']['input'];
      readonly updatedAt: CodecTypes['pg/timestamptz-temporal@1']['input'];
    };
    readonly receta: {
      readonly activa: CodecTypes['pg/bool@1']['input'];
      readonly codigo: CodecTypes['pg/text@1']['input'];
      readonly createdAt: CodecTypes['pg/timestamptz-temporal@1']['input'];
      readonly descripcion: CodecTypes['pg/text@1']['input'] | null;
      readonly id: CodecTypes['pg/text@1']['input'];
      readonly nombre: CodecTypes['pg/text@1']['input'];
      readonly rendimiento: CodecTypes['pg/float8@1']['input'];
      readonly unidadRendimiento: CodecTypes['pg/text@1']['input'];
      readonly updatedAt: CodecTypes['pg/timestamptz-temporal@1']['input'];
      readonly version: CodecTypes['pg/int4@1']['input'];
    };
    readonly usuario: {
      readonly activo: CodecTypes['pg/bool@1']['input'];
      readonly badge: CodecTypes['pg/text@1']['input'] | null;
      readonly createdAt: CodecTypes['pg/timestamptz-temporal@1']['input'];
      readonly email: CodecTypes['pg/text@1']['input'];
      readonly id: CodecTypes['pg/text@1']['input'];
      readonly nombre: CodecTypes['pg/text@1']['input'];
      readonly password: CodecTypes['pg/text@1']['input'];
      readonly rol: CodecTypes['pg/text@1']['input'];
    };
  };
};
export type TypeMaps = TypeMapsType<
  CodecTypes,
  QueryOperationTypes,
  FieldOutputTypes,
  FieldInputTypes,
  StorageColumnTypes,
  StorageColumnInputTypes,
  AggregateTypes
>;

type ContractBase = Omit<
  ContractType<{
    readonly namespaces: {
      readonly public: {
        readonly id: 'public';
        readonly kind: 'postgres-schema';
        readonly entries: {
          readonly table: {
            readonly auditoria: {
              columns: {
                readonly id: {
                  readonly nativeType: 'text';
                  readonly codecId: 'pg/text@1';
                  readonly nullable: false;
                };
                readonly usuarioId: {
                  readonly nativeType: 'text';
                  readonly codecId: 'pg/text@1';
                  readonly nullable: false;
                };
                readonly accion: {
                  readonly nativeType: 'text';
                  readonly codecId: 'pg/text@1';
                  readonly nullable: false;
                };
                readonly entidad: {
                  readonly nativeType: 'text';
                  readonly codecId: 'pg/text@1';
                  readonly nullable: false;
                };
                readonly entidadId: {
                  readonly nativeType: 'text';
                  readonly codecId: 'pg/text@1';
                  readonly nullable: false;
                };
                readonly detalles: {
                  readonly nativeType: 'text';
                  readonly codecId: 'pg/text@1';
                  readonly nullable: false;
                };
                readonly ip: {
                  readonly nativeType: 'text';
                  readonly codecId: 'pg/text@1';
                  readonly nullable: true;
                };
                readonly timestamp: {
                  readonly nativeType: 'timestamptz';
                  readonly codecId: 'pg/timestamptz-temporal@1';
                  readonly nullable: false;
                  readonly default: { readonly kind: 'function'; readonly expression: 'now()' };
                };
              };
              primaryKey: { readonly columns: readonly ['id'] };
              uniques: readonly [];
              indexes: readonly [
                {
                  readonly name: 'auditoria_usuarioId_idx_5f01c7d6';
                  readonly prefix: 'auditoria_usuarioId_idx';
                  readonly columns: readonly ['usuarioId'];
                  readonly unique: false;
                },
              ];
              foreignKeys: readonly [
                {
                  readonly source: {
                    readonly namespaceId: 'public' & NamespaceId;
                    readonly tableName: 'auditoria';
                    readonly columns: readonly ['usuarioId'];
                  };
                  readonly target: {
                    readonly namespaceId: 'public' & NamespaceId;
                    readonly tableName: 'usuario';
                    readonly columns: readonly ['id'];
                  };
                },
              ];
            };
            readonly dispensado: {
              columns: {
                readonly id: {
                  readonly nativeType: 'text';
                  readonly codecId: 'pg/text@1';
                  readonly nullable: false;
                };
                readonly ordenId: {
                  readonly nativeType: 'text';
                  readonly codecId: 'pg/text@1';
                  readonly nullable: false;
                };
                readonly loteId: {
                  readonly nativeType: 'text';
                  readonly codecId: 'pg/text@1';
                  readonly nullable: false;
                };
                readonly operarioId: {
                  readonly nativeType: 'text';
                  readonly codecId: 'pg/text@1';
                  readonly nullable: false;
                };
                readonly materialNombre: {
                  readonly nativeType: 'text';
                  readonly codecId: 'pg/text@1';
                  readonly nullable: false;
                };
                readonly cantidadTarget: {
                  readonly nativeType: 'float8';
                  readonly codecId: 'pg/float8@1';
                  readonly nullable: false;
                };
                readonly cantidadReal: {
                  readonly nativeType: 'float8';
                  readonly codecId: 'pg/float8@1';
                  readonly nullable: false;
                };
                readonly toleranciaOk: {
                  readonly nativeType: 'bool';
                  readonly codecId: 'pg/bool@1';
                  readonly nullable: false;
                };
                readonly paso: {
                  readonly nativeType: 'int4';
                  readonly codecId: 'pg/int4@1';
                  readonly nullable: false;
                };
                readonly firmaElectronica: {
                  readonly nativeType: 'text';
                  readonly codecId: 'pg/text@1';
                  readonly nullable: true;
                };
                readonly supervisorId: {
                  readonly nativeType: 'text';
                  readonly codecId: 'pg/text@1';
                  readonly nullable: true;
                };
                readonly timestamp: {
                  readonly nativeType: 'timestamptz';
                  readonly codecId: 'pg/timestamptz-temporal@1';
                  readonly nullable: false;
                  readonly default: { readonly kind: 'function'; readonly expression: 'now()' };
                };
              };
              primaryKey: { readonly columns: readonly ['id'] };
              uniques: readonly [];
              indexes: readonly [
                {
                  readonly name: 'dispensado_ordenId_idx_b087098b';
                  readonly prefix: 'dispensado_ordenId_idx';
                  readonly columns: readonly ['ordenId'];
                  readonly unique: false;
                },
                {
                  readonly name: 'dispensado_loteId_idx_cf903c78';
                  readonly prefix: 'dispensado_loteId_idx';
                  readonly columns: readonly ['loteId'];
                  readonly unique: false;
                },
                {
                  readonly name: 'dispensado_operarioId_idx_f3bec42d';
                  readonly prefix: 'dispensado_operarioId_idx';
                  readonly columns: readonly ['operarioId'];
                  readonly unique: false;
                },
              ];
              foreignKeys: readonly [
                {
                  readonly source: {
                    readonly namespaceId: 'public' & NamespaceId;
                    readonly tableName: 'dispensado';
                    readonly columns: readonly ['ordenId'];
                  };
                  readonly target: {
                    readonly namespaceId: 'public' & NamespaceId;
                    readonly tableName: 'ordenProduccion';
                    readonly columns: readonly ['id'];
                  };
                },
                {
                  readonly source: {
                    readonly namespaceId: 'public' & NamespaceId;
                    readonly tableName: 'dispensado';
                    readonly columns: readonly ['loteId'];
                  };
                  readonly target: {
                    readonly namespaceId: 'public' & NamespaceId;
                    readonly tableName: 'lote';
                    readonly columns: readonly ['id'];
                  };
                },
                {
                  readonly source: {
                    readonly namespaceId: 'public' & NamespaceId;
                    readonly tableName: 'dispensado';
                    readonly columns: readonly ['operarioId'];
                  };
                  readonly target: {
                    readonly namespaceId: 'public' & NamespaceId;
                    readonly tableName: 'usuario';
                    readonly columns: readonly ['id'];
                  };
                },
              ];
            };
            readonly ingrediente: {
              columns: {
                readonly id: {
                  readonly nativeType: 'text';
                  readonly codecId: 'pg/text@1';
                  readonly nullable: false;
                };
                readonly recetaId: {
                  readonly nativeType: 'text';
                  readonly codecId: 'pg/text@1';
                  readonly nullable: false;
                };
                readonly materialId: {
                  readonly nativeType: 'text';
                  readonly codecId: 'pg/text@1';
                  readonly nullable: false;
                };
                readonly orden: {
                  readonly nativeType: 'int4';
                  readonly codecId: 'pg/int4@1';
                  readonly nullable: false;
                };
                readonly cantidadTarget: {
                  readonly nativeType: 'float8';
                  readonly codecId: 'pg/float8@1';
                  readonly nullable: false;
                };
                readonly toleranciaMin: {
                  readonly nativeType: 'float8';
                  readonly codecId: 'pg/float8@1';
                  readonly nullable: false;
                };
                readonly toleranciaMax: {
                  readonly nativeType: 'float8';
                  readonly codecId: 'pg/float8@1';
                  readonly nullable: false;
                };
                readonly instrucciones: {
                  readonly nativeType: 'text';
                  readonly codecId: 'pg/text@1';
                  readonly nullable: true;
                };
                readonly peligroso: {
                  readonly nativeType: 'bool';
                  readonly codecId: 'pg/bool@1';
                  readonly nullable: false;
                  readonly default: {
                    readonly kind: 'literal';
                    readonly value: DefaultLiteralValue<'pg/bool@1', false>;
                  };
                };
              };
              primaryKey: { readonly columns: readonly ['id'] };
              uniques: readonly [];
              indexes: readonly [
                {
                  readonly name: 'ingrediente_recetaId_idx_a4de201c';
                  readonly prefix: 'ingrediente_recetaId_idx';
                  readonly columns: readonly ['recetaId'];
                  readonly unique: false;
                },
                {
                  readonly name: 'ingrediente_materialId_idx_e0f85a6d';
                  readonly prefix: 'ingrediente_materialId_idx';
                  readonly columns: readonly ['materialId'];
                  readonly unique: false;
                },
              ];
              foreignKeys: readonly [
                {
                  readonly source: {
                    readonly namespaceId: 'public' & NamespaceId;
                    readonly tableName: 'ingrediente';
                    readonly columns: readonly ['recetaId'];
                  };
                  readonly target: {
                    readonly namespaceId: 'public' & NamespaceId;
                    readonly tableName: 'receta';
                    readonly columns: readonly ['id'];
                  };
                },
                {
                  readonly source: {
                    readonly namespaceId: 'public' & NamespaceId;
                    readonly tableName: 'ingrediente';
                    readonly columns: readonly ['materialId'];
                  };
                  readonly target: {
                    readonly namespaceId: 'public' & NamespaceId;
                    readonly tableName: 'material';
                    readonly columns: readonly ['id'];
                  };
                },
              ];
            };
            readonly lote: {
              columns: {
                readonly id: {
                  readonly nativeType: 'text';
                  readonly codecId: 'pg/text@1';
                  readonly nullable: false;
                };
                readonly numero: {
                  readonly nativeType: 'text';
                  readonly codecId: 'pg/text@1';
                  readonly nullable: false;
                };
                readonly materialId: {
                  readonly nativeType: 'text';
                  readonly codecId: 'pg/text@1';
                  readonly nullable: false;
                };
                readonly cantidad: {
                  readonly nativeType: 'float8';
                  readonly codecId: 'pg/float8@1';
                  readonly nullable: false;
                };
                readonly cantidadInicial: {
                  readonly nativeType: 'float8';
                  readonly codecId: 'pg/float8@1';
                  readonly nullable: false;
                };
                readonly fechaRecepcion: {
                  readonly nativeType: 'timestamptz';
                  readonly codecId: 'pg/timestamptz-temporal@1';
                  readonly nullable: false;
                };
                readonly fechaCaducidad: {
                  readonly nativeType: 'timestamptz';
                  readonly codecId: 'pg/timestamptz-temporal@1';
                  readonly nullable: false;
                };
                readonly proveedor: {
                  readonly nativeType: 'text';
                  readonly codecId: 'pg/text@1';
                  readonly nullable: false;
                };
                readonly estado: {
                  readonly nativeType: 'text';
                  readonly codecId: 'pg/text@1';
                  readonly nullable: false;
                  readonly default: {
                    readonly kind: 'literal';
                    readonly value: DefaultLiteralValue<'pg/text@1', 'CUARENTENA'>;
                  };
                };
                readonly certificado: {
                  readonly nativeType: 'text';
                  readonly codecId: 'pg/text@1';
                  readonly nullable: true;
                };
                readonly createdAt: {
                  readonly nativeType: 'timestamptz';
                  readonly codecId: 'pg/timestamptz-temporal@1';
                  readonly nullable: false;
                  readonly default: { readonly kind: 'function'; readonly expression: 'now()' };
                };
              };
              primaryKey: { readonly columns: readonly ['id'] };
              uniques: readonly [{ readonly columns: readonly ['numero'] }];
              indexes: readonly [
                {
                  readonly name: 'lote_materialId_idx_e0f85a6d';
                  readonly prefix: 'lote_materialId_idx';
                  readonly columns: readonly ['materialId'];
                  readonly unique: false;
                },
              ];
              foreignKeys: readonly [
                {
                  readonly source: {
                    readonly namespaceId: 'public' & NamespaceId;
                    readonly tableName: 'lote';
                    readonly columns: readonly ['materialId'];
                  };
                  readonly target: {
                    readonly namespaceId: 'public' & NamespaceId;
                    readonly tableName: 'material';
                    readonly columns: readonly ['id'];
                  };
                },
              ];
            };
            readonly material: {
              columns: {
                readonly id: {
                  readonly nativeType: 'text';
                  readonly codecId: 'pg/text@1';
                  readonly nullable: false;
                };
                readonly codigo: {
                  readonly nativeType: 'text';
                  readonly codecId: 'pg/text@1';
                  readonly nullable: false;
                };
                readonly nombre: {
                  readonly nativeType: 'text';
                  readonly codecId: 'pg/text@1';
                  readonly nullable: false;
                };
                readonly descripcion: {
                  readonly nativeType: 'text';
                  readonly codecId: 'pg/text@1';
                  readonly nullable: true;
                };
                readonly unidad: {
                  readonly nativeType: 'text';
                  readonly codecId: 'pg/text@1';
                  readonly nullable: false;
                };
                readonly stockMinimo: {
                  readonly nativeType: 'float8';
                  readonly codecId: 'pg/float8@1';
                  readonly nullable: false;
                };
                readonly activo: {
                  readonly nativeType: 'bool';
                  readonly codecId: 'pg/bool@1';
                  readonly nullable: false;
                  readonly default: {
                    readonly kind: 'literal';
                    readonly value: DefaultLiteralValue<'pg/bool@1', true>;
                  };
                };
              };
              primaryKey: { readonly columns: readonly ['id'] };
              uniques: readonly [{ readonly columns: readonly ['codigo'] }];
              indexes: readonly [];
              foreignKeys: readonly [];
            };
            readonly ordenProduccion: {
              columns: {
                readonly id: {
                  readonly nativeType: 'text';
                  readonly codecId: 'pg/text@1';
                  readonly nullable: false;
                };
                readonly numero: {
                  readonly nativeType: 'text';
                  readonly codecId: 'pg/text@1';
                  readonly nullable: false;
                };
                readonly recetaId: {
                  readonly nativeType: 'text';
                  readonly codecId: 'pg/text@1';
                  readonly nullable: false;
                };
                readonly loteProducto: {
                  readonly nativeType: 'text';
                  readonly codecId: 'pg/text@1';
                  readonly nullable: false;
                };
                readonly cantidad: {
                  readonly nativeType: 'float8';
                  readonly codecId: 'pg/float8@1';
                  readonly nullable: false;
                };
                readonly estado: {
                  readonly nativeType: 'text';
                  readonly codecId: 'pg/text@1';
                  readonly nullable: false;
                  readonly default: {
                    readonly kind: 'literal';
                    readonly value: DefaultLiteralValue<'pg/text@1', 'PENDIENTE'>;
                  };
                };
                readonly prioridad: {
                  readonly nativeType: 'int4';
                  readonly codecId: 'pg/int4@1';
                  readonly nullable: false;
                  readonly default: {
                    readonly kind: 'literal';
                    readonly value: DefaultLiteralValue<'pg/int4@1', 0>;
                  };
                };
                readonly createdAt: {
                  readonly nativeType: 'timestamptz';
                  readonly codecId: 'pg/timestamptz-temporal@1';
                  readonly nullable: false;
                  readonly default: { readonly kind: 'function'; readonly expression: 'now()' };
                };
                readonly updatedAt: {
                  readonly nativeType: 'timestamptz';
                  readonly codecId: 'pg/timestamptz-temporal@1';
                  readonly nullable: false;
                  readonly default: { readonly kind: 'function'; readonly expression: 'now()' };
                };
              };
              primaryKey: { readonly columns: readonly ['id'] };
              uniques: readonly [{ readonly columns: readonly ['numero'] }];
              indexes: readonly [
                {
                  readonly name: 'ordenProduccion_recetaId_idx_a4de201c';
                  readonly prefix: 'ordenProduccion_recetaId_idx';
                  readonly columns: readonly ['recetaId'];
                  readonly unique: false;
                },
              ];
              foreignKeys: readonly [
                {
                  readonly source: {
                    readonly namespaceId: 'public' & NamespaceId;
                    readonly tableName: 'ordenProduccion';
                    readonly columns: readonly ['recetaId'];
                  };
                  readonly target: {
                    readonly namespaceId: 'public' & NamespaceId;
                    readonly tableName: 'receta';
                    readonly columns: readonly ['id'];
                  };
                },
              ];
            };
            readonly receta: {
              columns: {
                readonly id: {
                  readonly nativeType: 'text';
                  readonly codecId: 'pg/text@1';
                  readonly nullable: false;
                };
                readonly codigo: {
                  readonly nativeType: 'text';
                  readonly codecId: 'pg/text@1';
                  readonly nullable: false;
                };
                readonly nombre: {
                  readonly nativeType: 'text';
                  readonly codecId: 'pg/text@1';
                  readonly nullable: false;
                };
                readonly version: {
                  readonly nativeType: 'int4';
                  readonly codecId: 'pg/int4@1';
                  readonly nullable: false;
                  readonly default: {
                    readonly kind: 'literal';
                    readonly value: DefaultLiteralValue<'pg/int4@1', 1>;
                  };
                };
                readonly descripcion: {
                  readonly nativeType: 'text';
                  readonly codecId: 'pg/text@1';
                  readonly nullable: true;
                };
                readonly rendimiento: {
                  readonly nativeType: 'float8';
                  readonly codecId: 'pg/float8@1';
                  readonly nullable: false;
                };
                readonly unidadRendimiento: {
                  readonly nativeType: 'text';
                  readonly codecId: 'pg/text@1';
                  readonly nullable: false;
                };
                readonly activa: {
                  readonly nativeType: 'bool';
                  readonly codecId: 'pg/bool@1';
                  readonly nullable: false;
                  readonly default: {
                    readonly kind: 'literal';
                    readonly value: DefaultLiteralValue<'pg/bool@1', true>;
                  };
                };
                readonly createdAt: {
                  readonly nativeType: 'timestamptz';
                  readonly codecId: 'pg/timestamptz-temporal@1';
                  readonly nullable: false;
                  readonly default: { readonly kind: 'function'; readonly expression: 'now()' };
                };
                readonly updatedAt: {
                  readonly nativeType: 'timestamptz';
                  readonly codecId: 'pg/timestamptz-temporal@1';
                  readonly nullable: false;
                  readonly default: { readonly kind: 'function'; readonly expression: 'now()' };
                };
              };
              primaryKey: { readonly columns: readonly ['id'] };
              uniques: readonly [{ readonly columns: readonly ['codigo'] }];
              indexes: readonly [];
              foreignKeys: readonly [];
            };
            readonly usuario: {
              columns: {
                readonly id: {
                  readonly nativeType: 'text';
                  readonly codecId: 'pg/text@1';
                  readonly nullable: false;
                };
                readonly nombre: {
                  readonly nativeType: 'text';
                  readonly codecId: 'pg/text@1';
                  readonly nullable: false;
                };
                readonly email: {
                  readonly nativeType: 'text';
                  readonly codecId: 'pg/text@1';
                  readonly nullable: false;
                };
                readonly password: {
                  readonly nativeType: 'text';
                  readonly codecId: 'pg/text@1';
                  readonly nullable: false;
                };
                readonly rol: {
                  readonly nativeType: 'text';
                  readonly codecId: 'pg/text@1';
                  readonly nullable: false;
                  readonly default: {
                    readonly kind: 'literal';
                    readonly value: DefaultLiteralValue<'pg/text@1', 'OPERARIO'>;
                  };
                };
                readonly badge: {
                  readonly nativeType: 'text';
                  readonly codecId: 'pg/text@1';
                  readonly nullable: true;
                };
                readonly activo: {
                  readonly nativeType: 'bool';
                  readonly codecId: 'pg/bool@1';
                  readonly nullable: false;
                  readonly default: {
                    readonly kind: 'literal';
                    readonly value: DefaultLiteralValue<'pg/bool@1', true>;
                  };
                };
                readonly createdAt: {
                  readonly nativeType: 'timestamptz';
                  readonly codecId: 'pg/timestamptz-temporal@1';
                  readonly nullable: false;
                  readonly default: { readonly kind: 'function'; readonly expression: 'now()' };
                };
              };
              primaryKey: { readonly columns: readonly ['id'] };
              uniques: readonly [
                { readonly columns: readonly ['email'] },
                { readonly columns: readonly ['badge'] },
              ];
              indexes: readonly [];
              foreignKeys: readonly [];
            };
          };
        };
      };
    };
    readonly storageHash: StorageHash;
  }>,
  'roots' | 'domain'
> & {
  readonly target: 'postgres';
  readonly targetFamily: 'sql';
  readonly roots: {
    readonly usuario: { readonly namespace: 'public' & NamespaceId; readonly model: 'Usuario' };
    readonly material: { readonly namespace: 'public' & NamespaceId; readonly model: 'Material' };
    readonly lote: { readonly namespace: 'public' & NamespaceId; readonly model: 'Lote' };
    readonly receta: { readonly namespace: 'public' & NamespaceId; readonly model: 'Receta' };
    readonly ingrediente: {
      readonly namespace: 'public' & NamespaceId;
      readonly model: 'Ingrediente';
    };
    readonly ordenProduccion: {
      readonly namespace: 'public' & NamespaceId;
      readonly model: 'OrdenProduccion';
    };
    readonly dispensado: {
      readonly namespace: 'public' & NamespaceId;
      readonly model: 'Dispensado';
    };
    readonly auditoria: { readonly namespace: 'public' & NamespaceId; readonly model: 'Auditoria' };
  };
  readonly domain: {
    readonly namespaces: {
      readonly public: {
        readonly models: {
          readonly Auditoria: {
            readonly fields: {
              readonly id: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/text@1' };
              };
              readonly usuarioId: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/text@1' };
              };
              readonly accion: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/text@1' };
              };
              readonly entidad: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/text@1' };
              };
              readonly entidadId: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/text@1' };
              };
              readonly detalles: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/text@1' };
              };
              readonly ip: {
                readonly nullable: true;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/text@1' };
              };
              readonly timestamp: {
                readonly nullable: false;
                readonly type: {
                  readonly kind: 'scalar';
                  readonly codecId: 'pg/timestamptz-temporal@1';
                };
              };
            };
            readonly relations: {
              readonly usuario: {
                readonly to: {
                  readonly namespace: 'public' & NamespaceId;
                  readonly model: 'Usuario';
                };
                readonly cardinality: 'N:1';
                readonly on: {
                  readonly localFields: readonly ['usuarioId'];
                  readonly targetFields: readonly ['id'];
                };
              };
            };
            readonly storage: {
              readonly table: 'auditoria';
              readonly namespaceId: 'public';
              readonly fields: {
                readonly id: { readonly column: 'id' };
                readonly usuarioId: { readonly column: 'usuarioId' };
                readonly accion: { readonly column: 'accion' };
                readonly entidad: { readonly column: 'entidad' };
                readonly entidadId: { readonly column: 'entidadId' };
                readonly detalles: { readonly column: 'detalles' };
                readonly ip: { readonly column: 'ip' };
                readonly timestamp: { readonly column: 'timestamp' };
              };
            };
          };
          readonly Dispensado: {
            readonly fields: {
              readonly id: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/text@1' };
              };
              readonly ordenId: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/text@1' };
              };
              readonly loteId: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/text@1' };
              };
              readonly operarioId: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/text@1' };
              };
              readonly materialNombre: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/text@1' };
              };
              readonly cantidadTarget: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/float8@1' };
              };
              readonly cantidadReal: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/float8@1' };
              };
              readonly toleranciaOk: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/bool@1' };
              };
              readonly paso: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/int4@1' };
              };
              readonly firmaElectronica: {
                readonly nullable: true;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/text@1' };
              };
              readonly supervisorId: {
                readonly nullable: true;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/text@1' };
              };
              readonly timestamp: {
                readonly nullable: false;
                readonly type: {
                  readonly kind: 'scalar';
                  readonly codecId: 'pg/timestamptz-temporal@1';
                };
              };
            };
            readonly relations: {
              readonly lote: {
                readonly to: { readonly namespace: 'public' & NamespaceId; readonly model: 'Lote' };
                readonly cardinality: 'N:1';
                readonly on: {
                  readonly localFields: readonly ['loteId'];
                  readonly targetFields: readonly ['id'];
                };
              };
              readonly operario: {
                readonly to: {
                  readonly namespace: 'public' & NamespaceId;
                  readonly model: 'Usuario';
                };
                readonly cardinality: 'N:1';
                readonly on: {
                  readonly localFields: readonly ['operarioId'];
                  readonly targetFields: readonly ['id'];
                };
              };
              readonly orden: {
                readonly to: {
                  readonly namespace: 'public' & NamespaceId;
                  readonly model: 'OrdenProduccion';
                };
                readonly cardinality: 'N:1';
                readonly on: {
                  readonly localFields: readonly ['ordenId'];
                  readonly targetFields: readonly ['id'];
                };
              };
            };
            readonly storage: {
              readonly table: 'dispensado';
              readonly namespaceId: 'public';
              readonly fields: {
                readonly id: { readonly column: 'id' };
                readonly ordenId: { readonly column: 'ordenId' };
                readonly loteId: { readonly column: 'loteId' };
                readonly operarioId: { readonly column: 'operarioId' };
                readonly materialNombre: { readonly column: 'materialNombre' };
                readonly cantidadTarget: { readonly column: 'cantidadTarget' };
                readonly cantidadReal: { readonly column: 'cantidadReal' };
                readonly toleranciaOk: { readonly column: 'toleranciaOk' };
                readonly paso: { readonly column: 'paso' };
                readonly firmaElectronica: { readonly column: 'firmaElectronica' };
                readonly supervisorId: { readonly column: 'supervisorId' };
                readonly timestamp: { readonly column: 'timestamp' };
              };
            };
          };
          readonly Ingrediente: {
            readonly fields: {
              readonly id: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/text@1' };
              };
              readonly recetaId: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/text@1' };
              };
              readonly materialId: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/text@1' };
              };
              readonly orden: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/int4@1' };
              };
              readonly cantidadTarget: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/float8@1' };
              };
              readonly toleranciaMin: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/float8@1' };
              };
              readonly toleranciaMax: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/float8@1' };
              };
              readonly instrucciones: {
                readonly nullable: true;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/text@1' };
              };
              readonly peligroso: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/bool@1' };
              };
            };
            readonly relations: {
              readonly material: {
                readonly to: {
                  readonly namespace: 'public' & NamespaceId;
                  readonly model: 'Material';
                };
                readonly cardinality: 'N:1';
                readonly on: {
                  readonly localFields: readonly ['materialId'];
                  readonly targetFields: readonly ['id'];
                };
              };
              readonly receta: {
                readonly to: {
                  readonly namespace: 'public' & NamespaceId;
                  readonly model: 'Receta';
                };
                readonly cardinality: 'N:1';
                readonly on: {
                  readonly localFields: readonly ['recetaId'];
                  readonly targetFields: readonly ['id'];
                };
              };
            };
            readonly storage: {
              readonly table: 'ingrediente';
              readonly namespaceId: 'public';
              readonly fields: {
                readonly id: { readonly column: 'id' };
                readonly recetaId: { readonly column: 'recetaId' };
                readonly materialId: { readonly column: 'materialId' };
                readonly orden: { readonly column: 'orden' };
                readonly cantidadTarget: { readonly column: 'cantidadTarget' };
                readonly toleranciaMin: { readonly column: 'toleranciaMin' };
                readonly toleranciaMax: { readonly column: 'toleranciaMax' };
                readonly instrucciones: { readonly column: 'instrucciones' };
                readonly peligroso: { readonly column: 'peligroso' };
              };
            };
          };
          readonly Lote: {
            readonly fields: {
              readonly id: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/text@1' };
              };
              readonly numero: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/text@1' };
              };
              readonly materialId: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/text@1' };
              };
              readonly cantidad: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/float8@1' };
              };
              readonly cantidadInicial: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/float8@1' };
              };
              readonly fechaRecepcion: {
                readonly nullable: false;
                readonly type: {
                  readonly kind: 'scalar';
                  readonly codecId: 'pg/timestamptz-temporal@1';
                };
              };
              readonly fechaCaducidad: {
                readonly nullable: false;
                readonly type: {
                  readonly kind: 'scalar';
                  readonly codecId: 'pg/timestamptz-temporal@1';
                };
              };
              readonly proveedor: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/text@1' };
              };
              readonly estado: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/text@1' };
              };
              readonly certificado: {
                readonly nullable: true;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/text@1' };
              };
              readonly createdAt: {
                readonly nullable: false;
                readonly type: {
                  readonly kind: 'scalar';
                  readonly codecId: 'pg/timestamptz-temporal@1';
                };
              };
            };
            readonly relations: {
              readonly dispensados: {
                readonly to: {
                  readonly namespace: 'public' & NamespaceId;
                  readonly model: 'Dispensado';
                };
                readonly cardinality: '1:N';
                readonly on: {
                  readonly localFields: readonly ['id'];
                  readonly targetFields: readonly ['loteId'];
                };
              };
              readonly material: {
                readonly to: {
                  readonly namespace: 'public' & NamespaceId;
                  readonly model: 'Material';
                };
                readonly cardinality: 'N:1';
                readonly on: {
                  readonly localFields: readonly ['materialId'];
                  readonly targetFields: readonly ['id'];
                };
              };
            };
            readonly storage: {
              readonly table: 'lote';
              readonly namespaceId: 'public';
              readonly fields: {
                readonly id: { readonly column: 'id' };
                readonly numero: { readonly column: 'numero' };
                readonly materialId: { readonly column: 'materialId' };
                readonly cantidad: { readonly column: 'cantidad' };
                readonly cantidadInicial: { readonly column: 'cantidadInicial' };
                readonly fechaRecepcion: { readonly column: 'fechaRecepcion' };
                readonly fechaCaducidad: { readonly column: 'fechaCaducidad' };
                readonly proveedor: { readonly column: 'proveedor' };
                readonly estado: { readonly column: 'estado' };
                readonly certificado: { readonly column: 'certificado' };
                readonly createdAt: { readonly column: 'createdAt' };
              };
            };
          };
          readonly Material: {
            readonly fields: {
              readonly id: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/text@1' };
              };
              readonly codigo: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/text@1' };
              };
              readonly nombre: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/text@1' };
              };
              readonly descripcion: {
                readonly nullable: true;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/text@1' };
              };
              readonly unidad: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/text@1' };
              };
              readonly stockMinimo: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/float8@1' };
              };
              readonly activo: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/bool@1' };
              };
            };
            readonly relations: {
              readonly ingredientes: {
                readonly to: {
                  readonly namespace: 'public' & NamespaceId;
                  readonly model: 'Ingrediente';
                };
                readonly cardinality: '1:N';
                readonly on: {
                  readonly localFields: readonly ['id'];
                  readonly targetFields: readonly ['materialId'];
                };
              };
              readonly lotes: {
                readonly to: { readonly namespace: 'public' & NamespaceId; readonly model: 'Lote' };
                readonly cardinality: '1:N';
                readonly on: {
                  readonly localFields: readonly ['id'];
                  readonly targetFields: readonly ['materialId'];
                };
              };
            };
            readonly storage: {
              readonly table: 'material';
              readonly namespaceId: 'public';
              readonly fields: {
                readonly id: { readonly column: 'id' };
                readonly codigo: { readonly column: 'codigo' };
                readonly nombre: { readonly column: 'nombre' };
                readonly descripcion: { readonly column: 'descripcion' };
                readonly unidad: { readonly column: 'unidad' };
                readonly stockMinimo: { readonly column: 'stockMinimo' };
                readonly activo: { readonly column: 'activo' };
              };
            };
          };
          readonly OrdenProduccion: {
            readonly fields: {
              readonly id: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/text@1' };
              };
              readonly numero: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/text@1' };
              };
              readonly recetaId: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/text@1' };
              };
              readonly loteProducto: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/text@1' };
              };
              readonly cantidad: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/float8@1' };
              };
              readonly estado: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/text@1' };
              };
              readonly prioridad: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/int4@1' };
              };
              readonly createdAt: {
                readonly nullable: false;
                readonly type: {
                  readonly kind: 'scalar';
                  readonly codecId: 'pg/timestamptz-temporal@1';
                };
              };
              readonly updatedAt: {
                readonly nullable: false;
                readonly type: {
                  readonly kind: 'scalar';
                  readonly codecId: 'pg/timestamptz-temporal@1';
                };
              };
            };
            readonly relations: {
              readonly dispensados: {
                readonly to: {
                  readonly namespace: 'public' & NamespaceId;
                  readonly model: 'Dispensado';
                };
                readonly cardinality: '1:N';
                readonly on: {
                  readonly localFields: readonly ['id'];
                  readonly targetFields: readonly ['ordenId'];
                };
              };
              readonly receta: {
                readonly to: {
                  readonly namespace: 'public' & NamespaceId;
                  readonly model: 'Receta';
                };
                readonly cardinality: 'N:1';
                readonly on: {
                  readonly localFields: readonly ['recetaId'];
                  readonly targetFields: readonly ['id'];
                };
              };
            };
            readonly storage: {
              readonly table: 'ordenProduccion';
              readonly namespaceId: 'public';
              readonly fields: {
                readonly id: { readonly column: 'id' };
                readonly numero: { readonly column: 'numero' };
                readonly recetaId: { readonly column: 'recetaId' };
                readonly loteProducto: { readonly column: 'loteProducto' };
                readonly cantidad: { readonly column: 'cantidad' };
                readonly estado: { readonly column: 'estado' };
                readonly prioridad: { readonly column: 'prioridad' };
                readonly createdAt: { readonly column: 'createdAt' };
                readonly updatedAt: { readonly column: 'updatedAt' };
              };
            };
          };
          readonly Receta: {
            readonly fields: {
              readonly id: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/text@1' };
              };
              readonly codigo: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/text@1' };
              };
              readonly nombre: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/text@1' };
              };
              readonly version: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/int4@1' };
              };
              readonly descripcion: {
                readonly nullable: true;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/text@1' };
              };
              readonly rendimiento: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/float8@1' };
              };
              readonly unidadRendimiento: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/text@1' };
              };
              readonly activa: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/bool@1' };
              };
              readonly createdAt: {
                readonly nullable: false;
                readonly type: {
                  readonly kind: 'scalar';
                  readonly codecId: 'pg/timestamptz-temporal@1';
                };
              };
              readonly updatedAt: {
                readonly nullable: false;
                readonly type: {
                  readonly kind: 'scalar';
                  readonly codecId: 'pg/timestamptz-temporal@1';
                };
              };
            };
            readonly relations: {
              readonly ingredientes: {
                readonly to: {
                  readonly namespace: 'public' & NamespaceId;
                  readonly model: 'Ingrediente';
                };
                readonly cardinality: '1:N';
                readonly on: {
                  readonly localFields: readonly ['id'];
                  readonly targetFields: readonly ['recetaId'];
                };
              };
              readonly ordenes: {
                readonly to: {
                  readonly namespace: 'public' & NamespaceId;
                  readonly model: 'OrdenProduccion';
                };
                readonly cardinality: '1:N';
                readonly on: {
                  readonly localFields: readonly ['id'];
                  readonly targetFields: readonly ['recetaId'];
                };
              };
            };
            readonly storage: {
              readonly table: 'receta';
              readonly namespaceId: 'public';
              readonly fields: {
                readonly id: { readonly column: 'id' };
                readonly codigo: { readonly column: 'codigo' };
                readonly nombre: { readonly column: 'nombre' };
                readonly version: { readonly column: 'version' };
                readonly descripcion: { readonly column: 'descripcion' };
                readonly rendimiento: { readonly column: 'rendimiento' };
                readonly unidadRendimiento: { readonly column: 'unidadRendimiento' };
                readonly activa: { readonly column: 'activa' };
                readonly createdAt: { readonly column: 'createdAt' };
                readonly updatedAt: { readonly column: 'updatedAt' };
              };
            };
          };
          readonly Usuario: {
            readonly fields: {
              readonly id: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/text@1' };
              };
              readonly nombre: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/text@1' };
              };
              readonly email: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/text@1' };
              };
              readonly password: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/text@1' };
              };
              readonly rol: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/text@1' };
              };
              readonly badge: {
                readonly nullable: true;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/text@1' };
              };
              readonly activo: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/bool@1' };
              };
              readonly createdAt: {
                readonly nullable: false;
                readonly type: {
                  readonly kind: 'scalar';
                  readonly codecId: 'pg/timestamptz-temporal@1';
                };
              };
            };
            readonly relations: {
              readonly auditorias: {
                readonly to: {
                  readonly namespace: 'public' & NamespaceId;
                  readonly model: 'Auditoria';
                };
                readonly cardinality: '1:N';
                readonly on: {
                  readonly localFields: readonly ['id'];
                  readonly targetFields: readonly ['usuarioId'];
                };
              };
              readonly dispensados: {
                readonly to: {
                  readonly namespace: 'public' & NamespaceId;
                  readonly model: 'Dispensado';
                };
                readonly cardinality: '1:N';
                readonly on: {
                  readonly localFields: readonly ['id'];
                  readonly targetFields: readonly ['operarioId'];
                };
              };
            };
            readonly storage: {
              readonly table: 'usuario';
              readonly namespaceId: 'public';
              readonly fields: {
                readonly id: { readonly column: 'id' };
                readonly nombre: { readonly column: 'nombre' };
                readonly email: { readonly column: 'email' };
                readonly password: { readonly column: 'password' };
                readonly rol: { readonly column: 'rol' };
                readonly badge: { readonly column: 'badge' };
                readonly activo: { readonly column: 'activo' };
                readonly createdAt: { readonly column: 'createdAt' };
              };
            };
          };
        };
      };
    };
  };
  readonly capabilities: {
    readonly postgres: {
      readonly distinctOn: true;
      readonly jsonAgg: true;
      readonly lateral: true;
      readonly limit: true;
      readonly orderBy: true;
      readonly returning: true;
    };
    readonly sql: {
      readonly checkConstraint: true;
      readonly defaultInInsert: true;
      readonly enums: true;
      readonly lateral: true;
      readonly returning: true;
      readonly scalarList: true;
    };
  };
  readonly extensions: {};
  readonly execution: {
    readonly executionHash: ExecutionHash;
    readonly mutations: {
      readonly defaults: readonly [
        {
          readonly ref: {
            readonly namespace: 'public';
            readonly table: 'auditoria';
            readonly column: 'id';
          };
          readonly onCreate: { readonly kind: 'generator'; readonly id: 'uuidv4' };
        },
        {
          readonly ref: {
            readonly namespace: 'public';
            readonly table: 'dispensado';
            readonly column: 'id';
          };
          readonly onCreate: { readonly kind: 'generator'; readonly id: 'uuidv4' };
        },
        {
          readonly ref: {
            readonly namespace: 'public';
            readonly table: 'ingrediente';
            readonly column: 'id';
          };
          readonly onCreate: { readonly kind: 'generator'; readonly id: 'uuidv4' };
        },
        {
          readonly ref: {
            readonly namespace: 'public';
            readonly table: 'lote';
            readonly column: 'id';
          };
          readonly onCreate: { readonly kind: 'generator'; readonly id: 'uuidv4' };
        },
        {
          readonly ref: {
            readonly namespace: 'public';
            readonly table: 'material';
            readonly column: 'id';
          };
          readonly onCreate: { readonly kind: 'generator'; readonly id: 'uuidv4' };
        },
        {
          readonly ref: {
            readonly namespace: 'public';
            readonly table: 'ordenProduccion';
            readonly column: 'id';
          };
          readonly onCreate: { readonly kind: 'generator'; readonly id: 'uuidv4' };
        },
        {
          readonly ref: {
            readonly namespace: 'public';
            readonly table: 'receta';
            readonly column: 'id';
          };
          readonly onCreate: { readonly kind: 'generator'; readonly id: 'uuidv4' };
        },
        {
          readonly ref: {
            readonly namespace: 'public';
            readonly table: 'usuario';
            readonly column: 'id';
          };
          readonly onCreate: { readonly kind: 'generator'; readonly id: 'uuidv4' };
        },
      ];
    };
  };
  readonly meta: {};

  readonly profileHash: ProfileHash;
};

export type Contract = ContractWithTypeMaps<ContractBase, TypeMaps>;

export type Namespaces = Contract['storage']['namespaces'];
